config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get "/pages/:page" => "pages#show"

  get '/static_pages/coopkearney', to: 'static_pages#coopkearney', as: :coopkearney
  get '/static_pages/urbandalecoop', to: 'static_pages#urbandalecoop', as: :urbandalecoop
  get '/static_pages/coopgrandisland', to: 'static_pages#coopgrandisland', as: :coopgrandisland
  get '/static_pages/about', to: 'static_pages#about', as: :about
  get '/static_pages/sports', to: 'static_pages#sports', as: :sports
  get '/static_pages/menu', to: 'static_pages#menu', as: :menu
  get '/static_pages/specials', to: 'static_pages#specials', as: :specials
  get '/static_pages/contactus', to: 'static_pages#contactus', as: :contactus
  get '/static_pages/coopgrandislandmenu', to: 'static_pages#coopgrandislandmenu', as: :coopgrandislandmenu
  get '/static_pages/coopgrandislandcontactus', to: 'static_pages#coopgrandislandcontactus', as: :coopgrandislandcontactus
  get '/static_pages/urbandalecoopmenu', to: 'static_pages#urbandalecoopmenu', as: :urbandalecoopmenu
  get '/static_pages/contacturbandale', to: 'static_pages#contacturbandale', as: :contacturbandale
  get '/static_pages/coopwestdesmoines', to: 'static_pages#coopwestdesmoines', as: :coopwestdesmoines
  get '/static_pages/westcontactus', to: 'static_pages#westcontactus', as: :westcontactus
  get '/static_pages/westmenu', to: 'static_pages#westmenu', as: :westmenu
  get '/static_pages/join', to: 'static_pages#join', as: :join
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/footer_controller.rb
class FooterController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def coopkearney
    @skip_footer = true
  end

  def urbandalecoop
    @skip_footer = true
  end

  def coopwestdesmoines
    @skip_footer = true
  end

  def coopgrandisland
    @skip_footer = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chickencoop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
        <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= image_tag("chickencooplogo.png", alt: "logo", size: 30, class: 'd-inline-block align-top') %>
        <%= link_to 'Chicken Coop', root_url, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          </ul>
          <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'About Us', about_url, class:'nav-link' %>
              </li>

              <li class="nav-item">
                <%= link_to 'Join us!', join_url, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sport Links', sports_url, class: 'nav-link' %>
              </li>
          </ul>
        </div>
      </nav>


      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

    <%= yield %>
    <%= render "static_pages/footer" unless @skip_footer %>
  </body>
</html>

app/views/static_pages/_footer.html.erb
<br />

<div class="footer">
  <div class="container">
    <div class="row">
       <span class="align-middle">
          <%= link_to 'West Des Monies Menu', westmenu_url, class:"btn btn-primary" %>
          <%= link_to 'Coop Kearney Menu', menu_url, class:"btn btn-primary" %>
        </span>
        &nbsp
       <span class="align-baseline">
          <%= link_to 'Grand Island Menu', coopgrandislandmenu_url, class:"btn btn-primary" %>
          <%= link_to 'Urbandale Menu', urbandalecoopmenu_url, class:"btn btn-primary" %>
       </span>
    </div>
  </div>
</div>

app/views/static_pages/about.html.erb
<br />
<div class="col-sm-12 text-center">
  <div class="card">
    <div class="card-block">
      <p class="card-text">
        <div class="picture">
          <br />
          <div class="frosty col-5 offset-3 text-center">
            <br />
            <h3>About Us<h3>
          </div>
        </div>
        <br />
        <br />
        <div id ="shadow" class="booyah-box col-10 offset-1 text-center">
          <i><strong><%= image_tag("chickencooplogo.png", alt: "logo", size: 30) %>The Chicken Coop Sports Bar & Grill</i></strong>
          <i>was established in Kearney Nebraska March of 2002.
            With the success of the Kearney store, we have been able to expand to two more locations. One in Grand Island Nebraska opened February of 2004 and the other in West Des Moines Iowa opened July of 2005.
            We have many food items to choose from that will tickle your tonsils with the signature flavor that they provide.
            One of those items is our flame broiled buffalo wings.
            They are cooked over an open flame, then one of our homemade sauces is seared on to the wing to give it that one of a kind flavor.
            We offer home-style pizzas, burgers, salads, quesadillas, kid menu, and many other items.
            We also offer the best television sports viewing with all of your favorite sport packages. Need room to accommodate large groups?
            We offer convenient party areas at every location. Call today to book ahead.</i>
              </div>
            </div>
          </div>
        </div>

app/views/static_pages/contactus.html.erb
<br />
<br />
<div class="booyah-box col-10 offset-1 text-center">
  <%= image_tag("chickencooplogo.png", alt: "logo", class: "image-class", size: "150") %>
  <h3>Contact Us</h3>
--------------------------
  <br />
  <h5 id="color">If you have any questions or would like to book a party, please let us know at.</h5>

  <h6>Chicken Coop</h6>
  <h6>2115 Ave A</h6>
    <h6>Kearney, NE 68847</h6>
      <h6>Phone: (308) 338-8500</h6>
        <h6>Fax: (308) 237-8510</h6>

  <br />

  <ol id="color">Scott Bauer (General Manager)</ol>
  <ol id="color">Collin Nabity (Owner Manager)</ol>
</div>

app/views/static_pages/coopgrandisland.html.erb
<br />
<div id ="shadow" class="booyah-box col-10 offset-1 text-center">
      <h3><strong>Chicken Coop 120 East 3rd st. Grand Island, NE 68801</strong></h3>
      <%= image_tag("chickencooplogo.png", alt: "logo", class: "image-class", size: "150") %>

<html>
  <head>
    <style>
      /* Set the size of the div element that contains the map */
      #map {
        height: 400px;  /* The height is 400 pixels */
        width: 100%;  /* The width is the width of the web page */
       }
    </style>
  </head>
  <body>
    <!--The div element for the map -->
    <div id="map"></div>
    <script>
      // Initialize and add the map
      function initMap() {
        // The location of Uluru
        var grandisland = {lat: 40.925988285714, lng: -98.339749142857};
        // The map, centered at Uluru
        var map = new google.maps.Map(
            document.getElementById('map'), {zoom: 20, center: grandisland});
        // The marker, positioned at Uluru
        var marker = new google.maps.Marker({position: grandisland, map: map});
      }
    </script>
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA90TTkK7g7dpS7-Hk6Zzo61nYkjHyvdx4&callback=initMap">
    </script>
  </body>
</html>


      <br />
      <br />
      <div id="shadow" class="booyah-box col-10 offset-1 text-center">
      <p>  Located in downtown Grand Island at the corner of 3rd & Sycamore. The Chicken Coop is a unique combination of sports bar and microbrewery. Our Two story triple brick building built in 1886 provides an atmosphere like no other place in town. Brewmaster Trevor Schaben of Thunderhead Brewery, gold medal winner 2004 International brewing competition, Provides us with over ten differet types of beer, some of which are brewed right at this location. With excelent food. great beer and a clean historic atmosphere "The Coop" as the locals call us offer:</p>

      <ol>1. Large smoke free area</ol>
      <ol>2. Outside beer garden</ol>
      <ol>3. Family friendly environment</ol>
      <ol>4. Ability to accomodate large groups</ol>
      <ol>5. Private party room</ol>
      <ol>6. Open 7 days a week</ol>
      <br />
        <p>Phone Number: (308) 398-2500</p>
        <ol>Store Hours: 7 days a week opening daily at 11 a.m.</ol>

        <ol>Store Hours:(Sunday 12-10
          Monday-Saturday 11:00 to midnight)</ol>
    <br />
    <%= link_to 'Menu', coopgrandislandmenu_url, class:"btn btn-primary" %>
    <%= link_to 'Contact Us', coopgrandislandcontactus_url, class:"btn btn-primary" %>
  </div>
</div>

app/views/static_pages/coopgrandislandcontactus.html.erb
<br />
<br />
<div class="booyah-box col-10 offset-1 text-center">
  <%= image_tag("chickencooplogo.png", alt: "logo", class: "image-class", size: "150") %>
  <h3>Contact Us</h3>

  <br />
  <h5 id="color">If you have any questions or would like to book a party, please let us know at.</h5>
<br />
  <h6>Chicken Coop</h6>
  <h6>120 East 3rd st.</h6>
  <h6>Grand Island, NE 68801</h6>
  <h6>Phone: (308) 398-2500</h6>

  <br />

  <ol id="color">Dean Pegg(Owner Manager)</ol>
</div>

app/views/static_pages/coopwestdesmoines.html.erb
<br />

<div id ="shadow" class="booyah-box col-10 offset-1 text-center">
  <h3><strong>Coop West Des Moines</strong></h3>
  <%= image_tag("chickencooplogo.png", alt: "logo", class: "image-class", size: "150") %>

  <html>
    <head>
      <style>
        /* Set the size of the div element that contains the map */
        #map {
          height: 400px;  /* The height is 400 pixels */
          width: 100%;  /* The width is the width of the web page */
         }
      </style>
    </head>
    <body>
      <!--The div element for the map -->
      <div id="map"></div>
      <script>
        // Initialize and add the map
        function initMap() {
          // The location of Uluru
          var westdesmoines = {lat: 41.572276, lng: -93.730074};
          // The map, centered at Uluru
          var map = new google.maps.Map(
              document.getElementById('map'), {zoom: 20, center: westdesmoines});
          // The marker, positioned at Uluru
          var marker = new google.maps.Marker({position: westdesmoines, map: map});
        }
      </script>
      <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA90TTkK7g7dpS7-Hk6Zzo61nYkjHyvdx4&callback=initMap">
      </script>
    </body>
  </html>
  <br />
  <br />
  <div id ="shadow" class="booyah-box col-10 offset-1 text-center">
  <p>Located on the corner of EP True Parkway and Grand Avenue (in the Hy-vee Shopping Center), The Chicken Coop has a small town feel that makes everyone feel at home. We have a dining room that seats 104 and a full bar that seats 55.

    Our menu offers a little of everything. We serve everything from Chicken Wings, Nachos, Hamburgers, Ribs, Steaks, Salads and much more. Don't forget to check out our lunch specials, dinner specials and our children's menu.

    We have 23 High Definition Televisions. We carry the NFL Sunday Ticket, MLB Extra Innings, Comcast Sports, Fox Sports Package and ESPN Package.</p>


    Phone: (515) 223-0088

    <li>1960 Grand Ave. Suite 23
      West Des Moines, IA. 50265</li>
    <li>Store Hours: Open daily at 11 a.m</li>
    <br />
    <%= link_to 'Menu', westmenu_url, class:"btn btn-primary" %>
    <%= link_to 'Contact Us', westcontactus_url, class:"btn btn-primary" %>
  </div>
</div>

app/views/static_pages/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
       <%= image_tag 'slider1.jpg', class: 'd-block img-fluid' %>
       <div class="carousel-caption d-none d-md-block">
         <h3>Chicken Coop Sports bar & Grill</h3>
       </div>
    </div>
    <div class="carousel-item">
       <%= image_tag 'slider2.jpg', class: 'd-block img-fluid' %>
       <div class="carousel-caption d-none d-md-block">
         <h3>Chicken Coop Sports bar & Grill</h3>
       </div>
    </div>
    <div class="carousel-item">
       <%= image_tag 'slider3.jpg', class: 'd-block img-fluid' %>
       <div class="carousel-caption d-none d-md-block">
         <h3>Chicken Coop Sports bar & Grill</h3>
       </div>
    </div>
    <div class="carousel-item">
       <%= image_tag 'slider4.jpg', class: 'd-block img-fluid' %>
       <div class="carousel-caption d-none d-md-block">
         <h3>Chicken Coop Sports bar & Grill</h3>
       </div>
    </div>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>



<br />
<br />


<div class="row feature text-center bottom-feature">

  <div class="col-sm-4">
    <div class="card">
      <%= image_tag("image1.png", alt: "logo", class: 'card-img-top img-fluid') %>
      <div class="card-block">
        <%= link_to 'Coop Kearney', coopkearney_url, class:"btn btn-primary" %>
        <br />
        <br />
        <p class="card-text">We have a non-smoking dining room that seats 95 and A full bar lounge area that seats 30. We have a large liquor selection with 15 beers on tap. A huge game room area with 4 pool tables, 4 dart boards, 2 foosball tables and other arcade games. A digital juke box with thousands of songs on demand. game room area has seating for parties up to 100 people with there own set of TV'sWe have 27 TVs (7 are High Definition). We carry the NFL Sunday Ticket, MLB Extra Innings, ESPN Game Plan College Football, ESPN Full court College BasketBall, MEGA March Madness, ESPN Package and the Fox Sports Package.
          Call Scott or Collin and reserve today. No charge for reserving parties.</p>
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="card">
      <%= image_tag("image3.png", alt: "logo", class: 'card-img-top img-fluid') %>
      <div class="card-block">
        <%= link_to 'Urbandale Coop', urbandalecoop_url, class:"btn btn-primary" %>
        <br />
        <br />
        <p class="card-text">Located on 128th and Meredith Drive in Urbandale. The Chicken Coop was opened in April of 2012 and offers a full menu and enough TV's to watch almost any sporting event. There is a daily lunch and drink specials. We carry the Sunday NFL Ticket, MLB Extra Innings, Comcast Sports, Fox Sports Package, Big Ten Network, Golf Network and the SEC Network.</p>
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="card">
      <%= image_tag("image4.png", alt: "logo", class: 'card-img-top img-fluid') %>
      <div class="card-block">
        <%= link_to 'West Des Moines', coopwestdesmoines_url, class:"btn btn-primary" %>
        <br />
        <br />
        <p class="card-text">Located on the corner of EP True Parkway and Grand Avenue (in the Hy-vee Shopping Center), The Chicken Coop has a small town feel that makes everyone feel at home. We have a dining room that seats 104 and a full bar that seats 55.
          Our menu offers a little of everything. Don't forget to check out our lunch specials, dinner specials.</p>
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="card">
      <%= image_tag("image2.png", alt: "logo", class: 'card-img-top img-fluid') %>
      <div class="card-block">
        <%= link_to 'Coop Grand Island', coopgrandisland_url, class:"btn btn-primary" %>
        <br />
        <br />
        <p class="card-text">Located in downtown Grand Island at the corner of 3rd & Sycamore. The Chicken Coop is a unique combination of sports bar and microbrewery. Our Two story triple brick building built in 1886 provides an atmosphere like no other place in town. Brewmaster Trevor Schaben of Thunderhead Brewery, gold medal winner 2004 International brewing competition, Provides us with over ten differet types of beer, some of which are brewed right at this location. With excelent food. great beer and a clean historic atmosphere "The Coop" as the locals call us offer:
        <dd>1. Large smoke free area</dd>
        <dd>2. Outside beer garden</dd>
        <dd>3. Family friendly environment</dd>
        <dd>4. Ability to accomodate large groups</dd>
        <dd>5. Private party room</dd>
        <dd>6. Open 7 days a week </dd></p>
      </div>
    </div>
  </div>


  <script>
    $('.carousel').carousel({
      interval: 3000
    })
  </script>
</div>

app/views/static_pages/join.html.erb
<br />
<br />
<div class="booyah-box col-10 offset-1 text-center">
    <%= image_tag("chickencooplogo.png", alt: "logo", class: "image-class", size: "150") %>
  <h3>Want to join the flock?</h3>

     <li>Are you intrested in a fun filled and exciting job with team coop. Each location is a independent operator where an owner/manager leads their team. We are interested in highly motivated individuals who want to provide our high quality of foods,drinks and service.</li>
     <h8><%= link_to "Download resume here", asset_path("The_Chicken_Coop_Application.pdf") %></h8>
  <br />
  <br />
  <div class="row feature text-center bottom-feature">

    <div class="col-sm-4">
      <div class="card">
        <div class="card-block">
          <h5>Coop Kearney
              2115 Ave A
              Kearney, NE 68847</h5>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card">
        <div class="card-block">
          <h5>Coop Grand Island
              120 East 3 St.
              Grand Island, NE 68801</h5>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card">
        <div class="card-block">
          <h5>Coop West DesMoines
              1960 Grand Ave #23
              West DesMoines, IA 50265</h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/specials.html.erb
<br />

<div id="shadow" class="booyah-box col-10 offset-1 text-center">
<%= image_tag("chickencooplogo.png", alt: "logo", class: "image-class", size: "150") %>
  <h3 id="red">SPECIALS</h3>

  <br />

  <h5>Kearney Lunch Specials</h5>

  <br />

  <h6>Monday:</h6>
  <i>Steak Sandwich with choice of side item: $7.99</i>

  <br />
  <br />

  <h6>Tuesday:</h6>
  <i>Any Chicken or Taco Salad with Choice of Ice Tea or soda for $7.49</i>

  <br />
  <br />

  <h6>Wednesday:</h6>
  <i>Turkey BLT Sandwich with choice of side item for $6.99</i>

  <br />
  <br />

  <h6>Thursday:</h6>
  <i>Poboy Shrimp Sandwich with choice of side item for $6.99</i>

  <br />
  <br />

  <h6>Friday:</h6>
  <i>Prime Rib Sandwich with choice of side item for $8.79</i>

  <br />
  <br />

  <h6>Saturday:</h6>
  <i>Pulled Pork Sandwich with choice of side item for $6.99</i>

  <br />
  <br />

  <h6>Sunday:</h6>
  <i>Chicken Fried Steak with Mash Potatoes and Corn $8.99</i>

  <br />
  <br />
  <i id ="red">JOIN OUR TEXT CLUB
    TEXT PBA COOP TO 28444 FOR WEEKLEY UPDATES ON OUR HOME STYLE LUNCH SPECIALS</i>
</div>

app/views/static_pages/sports.html.erb
<br />
<div class="col-sm-12 text-center">
  <div class="card">
    <div class="card-block">
      <p class="card-text">
        <div class="sports">
          <br />
          <div class="frosty col-8 offset-2 text-center">
            <br />
            <h3>Sport Links<h3>
          </div>
        </div>
----------------------


      <br />
      <br />
      <div class="booyah-box col-10 offset-1 text-center">
       <h5>Local Nebraska Sports:</h5>
       <dl><a href="https://www.Huskers.com">Huskers</a></dl>
       <dl><a href="https://www.Lopers.com">Lopers</a></dl>
       <dl><a href="https://www.Journalstar.com">Journalstar</a></dl>
       <dl><a href="https://www.theindependent.com">TheIndependent</a></dl>
       <dl><a href="https://www.Kearneyhub.com">Kearneyhub</a></dl>
       <dl>Creighton Uni.</dl>
       <dl>Hastings College</dl>

       <br />

       <h5>Local Iowa Sports:</h5>
       <dl><a href="https://www.cyclones.com">Cyclones</a></dl>
       <dl><a href="https://hawkeyesports.com">Hawkeyesports</a></dl>
       <dl><a href="https://www.desmoinesregister.com">Desmoinesregister</a></dl>
       <dl><a href="https://www.unipanthers.com">Unipanthers</a></dl>
       <br />

       <h5>General Sports:</h5>
       <dl><a href="https://www.cstv.com">CSTV</a></dl>
       <dl><a href="https://www.ESPN.com">ESPN</a></dl>
       <dl><a href="https://cbs.Sportsline.com">Sportsline</a></dl>
       <dl><a href="https://www.Foxsports.com">Foxsports</a></dl>

       <br />

       <h5>Football:</h5>
        <dl><a href="https://www.NFL.com">NFL.com</a></dl>

        <br />

       <h5>Hockey:</h5>
        <dl><a href="https://www.NHL.com">NHL.com</a></dl>

        <br />

       <h5>Soccer:</h5>
       <dl><a href="https://www.Menacesoccer.com">Menacesoccer</a></dl>
       <dl><a href="https://www.Drakebulldogs.org">Drakebulldogs</a></dl>

       <br />

       <h5>Baseball:</h5>
        <dl><a href="https://www.MLB.com">MLB</a></dl>
        <br />

       <h5>Basketball:</h5>
       <dl><a href="https://www.NBA.com">NBA</a></dl>

       <br />

       <h5>Racing:</h5>
        <dl><a href="https://www.Nascar.com">Nascar</a></dl>

        <br />

       <h5>Golf:</h5>
        <dl><a href="https://www.PGA.com">PGA</a></dl>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/urbandalecoop.html.erb
<br />
<div id ="shadow" class="booyah-box col-10 offset-1 text-center">
      <h3><strong>Chicken Coop 12725 Meredith Drive Urbandale, IA. 50323</strong></h3>
      <%= image_tag("chickencooplogo.png", alt: "logo", class: "image-class", size: "150") %>

        <html>
          <head>
            <style>
              /* Set the size of the div element that contains the map */
              #map {
                height: 400px;  /* The height is 400 pixels */
                width: 100%;  /* The width is the width of the web page */
               }
            </style>
          </head>
          <body>
            <!--The div element for the map -->
            <div id="map"></div>
            <script>
              // Initialize and add the map
              function initMap() {
                // The location of Uluru
                var urbandale = {lat: 41.6443605, lng: -93.7929048};
                // The map, centered at Uluru
                var map = new google.maps.Map(
                    document.getElementById('map'), {zoom: 20, center: urbandale});
                // The marker, positioned at Uluru
                var marker = new google.maps.Marker({position: urbandale, map: map});
              }
            </script>
            <script async defer
              src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA90TTkK7g7dpS7-Hk6Zzo61nYkjHyvdx4&callback=initMap">
            </script>
          </body>
        </html>
      <br />
      <br />
      <div id ="shadow" class="booyah-box col-10 offset-1 text-center">
      <p>Located on 128th and Meredith Drive in Urbandale.
        The Chicken Coop was opened in April of 2012 and offers a full menu and enough TV's to watch almost any sporting event.
        Our menu offers items anywhere from Wings to Steaks and Burgers to Ribs. There is a childrens menu and daily lunch and drink specials.
        We carry the Sunday NFL Ticket, MLB Extra Innings, Comcast Sports, Fox Sports Package, Big Ten Network, Golf Network and the SEC Network.
        We also televise some UFC PPV.</p>

        <p>Phone Number: (515) 334-COOP (2667)</p>
        <li>Store Hours:
        7 days a week opening daily at 11 a.m.</li>

        <li>Kitchen hours:
        11 a.m. to 10 p.m.</li>

    <br />
    <%= link_to 'Menu', urbandalecoopmenu_url, class:"btn btn-primary" %>
    <%= link_to 'Contact Us', contacturbandale_url, class:"btn btn-primary" %>
  </div>
</div>

app/views/static_pages/westcontactus.html.erb
<br />
<br />
<div id ="shadow" class="booyah-box col-10 offset-1 text-center">
  <%= image_tag("chickencooplogo.png", alt: "logo", class: "image-class", size: "150") %>
  <h3>Contact Us</h3>
------------------------
  <br />
  <h5 id="color">If you have any questions or would like to book a party, please let us know at:</h5>
  <br>
  <h6>Chicken Coop</h6>
  <h6>1960 Grand Ave #23</h6>
  <h6>West Desmoines, IA 50265</h6>
  <h6>Phone: (515) 223-0088</h6>

  <br />

  <ol id="color">Dawn Beister (Owner Manager)</ol>
  <ol id="color">Ken Beister (Owner Manager)</ol>
</div>